<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-08-14T00:32:35Z" name="Default suite" finished-at="2018-08-14T00:32:46Z" duration-ms="10350">
    <groups>
    </groups>
    <test started-at="2018-08-14T00:32:35Z" name="Default test" finished-at="2018-08-14T00:32:46Z" duration-ms="10350">
      <class name="JDBC.TestConnection1">
        <test-method is-config="true" signature="ServerConncetion()[pri:0, instance:JDBC.TestConnection1@7a419da4]" started-at="2018-08-14T00:32:35Z" name="ServerConncetion" finished-at="2018-08-14T00:32:46Z" duration-ms="10274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ServerConncetion -->
        <test-method signature="dataRetieveFromEmplyeeDable()[pri:0, instance:JDBC.TestConnection1@7a419da4]" started-at="2018-08-14T00:32:46Z" name="dataRetieveFromEmplyeeDable" finished-at="2018-08-14T00:32:46Z" duration-ms="58" status="FAIL">
          <exception class="java.sql.SQLException">
            <message>
              <![CDATA[No suitable driver found for jdbc.sqlserver://DESKTOPMSEDGEWIN10/SQLEXPRESSsa1234]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLException: No suitable driver found for jdbc.sqlserver://DESKTOPMSEDGEWIN10/SQLEXPRESSsa1234
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
at JDBC.TestConnection1.dataRetieveFromEmplyeeDable(TestConnection1.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataRetieveFromEmplyeeDable -->
      </class> <!-- JDBC.TestConnection1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
